CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "email" varchar(30) NOT NULL,
  "password" varchar(30) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar(30) NOT NULL,
  "level" int NOT NULL,
  "teacher" int NOT NULL,
  "course_video_id" int NOT NULL
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(300) NOT NULL,
  "category_id" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id");

ALTER TABLE "course_video" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("course_video_id") REFERENCES "course_video" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level") REFERENCES "level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher") REFERENCES "users" ("id");


INSERT INTO roles (name) VALUES ('admin');
INSERT INTO users (name, email, password, age, rol_id) VALUES ('juan', 'juan@gmail.com', '1234', 26, 1);
INSERT INTO users (name, email, password, age, rol_id) VALUES ('esteban', 'este@gmail.com', '1235', 56, 1);
INSERT INTO level (name) VALUES ('Beginner'),('Intermediate'),('Advanced');
INSERT INTO categories (name) VALUES ('Nodejs');\
INSERT INTO courses (description, level, teacher, course_video_id) VALUES ('all of nodejs', 1, 1, 1);
INSERT INTO courses (description, level, teacher, course_video_id) VALUES ('all of vuejs', 3, 1, 2);
INSERT INTO course_video (title, url, category_id) VALUES ('init nodejs', 'www.com', 1);
INSERT INTO course_video (title, url, category_id) VALUES ('init vuejs','www.net', 2);

-- entregable 1 listo 